services:
  db:
    image: postgres:15
    container_name: my_postgres
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - .src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
